<?php

use Inertia\Testing\AssertableInertia as Assert;

test('pricing page exposes all public plans and comparison sections', function () {
    $this->get(route('pricing'))
        ->assertOk()
        ->assertInertia(fn (Assert $page) => $page
            ->component('Pricing')
            ->where('megaMenu.display_location', 'header')
            ->where('footerMenu.display_location', 'footer')
            ->where('footerSection.layout', 'footer')
            ->where('defaultAudience', 'solo')
            ->has('pricingCatalogs.solo.plans', 3)
            ->where('pricingCatalogs.solo.plans.0.key', 'solo_essential')
            ->where('pricingCatalogs.solo.plans.1.key', 'solo_pro')
            ->where('pricingCatalogs.solo.plans.2.key', 'solo_growth')
            ->where('pricingCatalogs.solo.highlightedPlanKey', 'solo_pro')
            ->has('pricingCatalogs.solo.comparisonSections', 3)
            ->has('pricingCatalogs.solo.comparisonSections.0.rows', 6)
            ->where('pricingCatalogs.solo.comparisonSections.0.rows.0.values.0.plan_key', 'solo_essential')
            ->where('pricingCatalogs.solo.comparisonSections.0.rows.0.values.2.plan_key', 'solo_growth')
            ->where('pricingCatalogs.solo.comparisonSections.0.rows.1.values.0.text', 'Unlimited')
            ->where('pricingCatalogs.solo.comparisonSections.0.rows.2.values.1.text', 'Unlimited')
            ->where('pricingCatalogs.solo.comparisonSections.0.rows.3.values.2.text', 'Unlimited')
            ->where('pricingCatalogs.solo.comparisonSections.0.rows.4.values.0.type', 'included')
            ->where('pricingCatalogs.solo.comparisonSections.0.rows.4.values.1.type', 'included')
            ->where('pricingCatalogs.solo.comparisonSections.0.rows.4.values.2.type', 'included')
            ->where('pricingCatalogs.solo.comparisonSections.0.rows.5.values.0.text', 'Unlimited')
            ->has('pricingCatalogs.team.plans', 5)
            ->where('pricingCatalogs.team.plans.0.key', 'free')
            ->where('pricingCatalogs.team.plans.1.key', 'starter')
            ->where('pricingCatalogs.team.plans.2.key', 'growth')
            ->where('pricingCatalogs.team.plans.3.key', 'scale')
            ->where('pricingCatalogs.team.plans.4.key', 'enterprise')
            ->where('pricingCatalogs.team.highlightedPlanKey', 'growth')
            ->has('pricingCatalogs.team.comparisonSections', 3)
            ->has('pricingCatalogs.team.comparisonSections.0.rows', 8)
            ->where('pricingCatalogs.team.comparisonSections.0.rows.0.values.0.plan_key', 'free')
            ->where('pricingCatalogs.team.comparisonSections.0.rows.0.values.4.plan_key', 'enterprise')
            ->where('pricingCatalogs.team.comparisonSections.0.rows.2.values.0.text', 'Unlimited')
            ->where('pricingCatalogs.team.comparisonSections.0.rows.3.values.0.text', 'Unlimited')
            ->where('pricingCatalogs.team.comparisonSections.0.rows.4.values.0.text', 'Unlimited')
            ->where('pricingCatalogs.team.comparisonSections.0.rows.5.values.0.type', 'included')
            ->where('pricingCatalogs.team.comparisonSections.0.rows.5.values.4.type', 'included')
            ->has('pricingPlans', 3)
            ->where('pricingPlans.0.key', 'solo_essential')
            ->where('highlightedPlanKey', 'solo_pro')
            ->has('comparisonSections', 3)
        );
});
