<?php

use App\Services\Demo\Scenarios\StudioNaya\StudioNayaBlueprint;
use App\Services\Demo\Scenarios\StudioNaya\StudioNayaScenario;

return [
    'default_scenario' => env('DEMO_SCENARIO_DEFAULT', StudioNayaBlueprint::KEY),
    'default_volume' => env('DEMO_SCENARIO_VOLUME', StudioNayaBlueprint::DEFAULT_VOLUME),
    'reference_timezone' => env('DEMO_SCENARIO_TIMEZONE', 'America/Toronto'),
    'default_seed' => (int) env('DEMO_SCENARIO_SEED', 26082026),

    'volumes' => [
        'small' => [
            'employees' => 5,
            'services' => 28,
            'products' => 18,
            'customers' => 40,
            'reservations' => 180,
            'invoices' => 110,
            'payments' => 145,
            'quotes' => 10,
            'sales' => 35,
            'expenses' => 54,
            'inventory_movements' => 160,
            'notifications' => 12,
            'mailing_lists' => 2,
            'mailing_list_memberships' => 24,
            'campaigns' => 3,
            'campaign_channels' => 3,
            'campaign_audiences' => 3,
            'campaign_runs' => 1,
            'campaign_recipients' => 12,
            'campaign_messages' => 12,
            'campaign_events' => 54,
            'promotions' => 2,
            'promotion_usages' => 6,
            'assistant_settings' => 1,
            'assistant_knowledge_items' => 4,
            'assistant_conversations' => 6,
            'assistant_messages' => 18,
            'assistant_actions' => 3,
            'social_accounts' => 1,
            'social_templates' => 3,
            'social_posts' => 6,
            'social_targets' => 6,
            ...StudioNayaBlueprint::immersiveTargetsForVolume('small'),
        ],
        'medium' => [
            'employees' => 5,
            'services' => 28,
            'products' => 18,
            'customers' => 300,
            'reservations' => 1800,
            'invoices' => 1100,
            'payments' => 1450,
            'quotes' => 55,
            'sales' => 300,
            'expenses' => 216,
            'inventory_movements' => 2400,
            'notifications' => 36,
            'mailing_lists' => 3,
            'mailing_list_memberships' => 120,
            'campaigns' => 6,
            'campaign_channels' => 6,
            'campaign_audiences' => 6,
            'campaign_runs' => 2,
            'campaign_recipients' => 60,
            'campaign_messages' => 60,
            'campaign_events' => 270,
            'promotions' => 4,
            'promotion_usages' => 30,
            'assistant_settings' => 1,
            'assistant_knowledge_items' => 6,
            'assistant_conversations' => 24,
            'assistant_messages' => 72,
            'assistant_actions' => 12,
            'social_accounts' => 1,
            'social_templates' => 4,
            'social_posts' => 18,
            'social_targets' => 18,
            ...StudioNayaBlueprint::immersiveTargetsForVolume('medium'),
        ],
        'large' => [
            'employees' => 5,
            'services' => 28,
            'products' => 18,
            'customers' => 750,
            'reservations' => 6000,
            'invoices' => 3900,
            'payments' => 5000,
            'quotes' => 180,
            'sales' => 1100,
            'expenses' => 480,
            'inventory_movements' => 8000,
            'notifications' => 100,
            'mailing_lists' => 4,
            'mailing_list_memberships' => 300,
            'campaigns' => 9,
            'campaign_channels' => 9,
            'campaign_audiences' => 9,
            'campaign_runs' => 3,
            'campaign_recipients' => 180,
            'campaign_messages' => 180,
            'campaign_events' => 810,
            'promotions' => 6,
            'promotion_usages' => 90,
            'assistant_settings' => 1,
            'assistant_knowledge_items' => 8,
            'assistant_conversations' => 60,
            'assistant_messages' => 180,
            'assistant_actions' => 30,
            'social_accounts' => 1,
            'social_templates' => 5,
            'social_posts' => 36,
            'social_targets' => 36,
            ...StudioNayaBlueprint::immersiveTargetsForVolume('large'),
        ],
    ],

    'scenarios' => [
        StudioNayaBlueprint::KEY => [
            'blueprint' => StudioNayaBlueprint::class,
            'generator' => StudioNayaScenario::class,
            'default_volume' => StudioNayaBlueprint::DEFAULT_VOLUME,
            'available_volumes' => ['small', 'medium', 'large'],
            'required_modules' => [
                'services',
                'reservations',
                'planning',
                'presence',
                'invoices',
                'expenses',
                'accounting',
                'team_members',
                'performance',
                'products',
                'sales',
                'quotes',
                'tasks',
                'loyalty',
                'campaigns',
                'promotions',
                'assistant',
                'social',
            ],
            'history_months' => 18,
            'future_weeks' => 6,
            'reference_timezone' => 'America/Toronto',
        ],
    ],
];
