<?php

return [
    'groups' => [
        // Public pages can render without exposing the back-office, portal or API route map.
        'public' => [
            'welcome',
            'pricing',
            'terms',
            'privacy',
            'refund',
            'sitemap',
            'favicon',
            'public.*',
            'campaigns.track',
            'campaigns.unsubscribe',
            'login',
            'register',
            'logout',
            'onboarding.*',
            'password.*',
            'two-factor.*',
            'verification.*',
            'auth.social.*',
            'locale.update',
            'demo.*',
        ],

        // The client portal is combined with the public group by the resolver.
        'portal' => [
            'portal.*',
            'client.reservations.*',
            'dashboard',
            'profile.*',
            'password.update',
            'verification.send',
            'notifications.*',
            'locale.update',
            'logout',
            'demo.*',
        ],

        // Internal workspace and platform administration deliberately share one SPA surface.
        'admin' => [
            'accounting.*',
            'admin.*',
            'ai.*',
            'assistant.*',
            'campaign-automations.*',
            'campaign-runs.*',
            'campaigns.*',
            'catalog.*',
            'crm.*',
            'customer.*',
            'dashboard',
            'dashboard.*',
            'demo.*',
            'expense.*',
            'finance-approvals.*',
            'global.*',
            'invoice.*',
            'jobs.*',
            'loyalty.*',
            'marketing.*',
            'my-earnings.*',
            'notifications.*',
            'offer-packages.*',
            'offers.*',
            'orders.*',
            'payment.*',
            'payments.*',
            'performance.*',
            'pipeline.*',
            'plan-scans.*',
            'planning.*',
            'presence.*',
            'product.*',
            'profile.*',
            'promotions.*',
            'prospects.*',
            'quote.*',
            'request.*',
            'reservation.*',
            'sales.*',
            'service-requests.*',
            'service.*',
            'settings.*',
            'social.*',
            'superadmin.*',
            'task.*',
            'tasks.*',
            'team.*',
            'work.*',
            'workspace.*',
            'login',
            'register',
            'logout',
            'onboarding.*',
            'password.*',
            'two-factor.*',
            'verification.*',
            'auth.social.*',
            'locale.update',
        ],
    ],
];
